### ISSUE TITLE
Option to disable preloader

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/oria#32]
Similar to how it is in shopisle and zerif

**Comment by rodica-andronache** [comment]
@dragosey just as a suggestion, instead of
```
global $wp_customize;
if ( ! isset( $wp_customize ) ) 
```
is better to use
https://developer.wordpress.org/reference/functions/is_customize_preview/ which checks if you are in customizer

Also, right now, by default the option in customizer, is checked, while on the site the preloader is displaying. This is happening, because in customizer you gave it a default value of '1' , but when you get it with `$oria_disable_preloader = get_theme_mod( 'oria_disable_preloader' );` there is no default value.

In this case, you shouldn't give it a default value at all, I think because by default you want to keep the same behaviour as before, to display the preloader.

I would also remove the description of the control, because for themes hosted on wordpress.org, we are trying to add as few strings as possible, to keep translations up.

**Comment by dragosey** [comment]
@rodica-andronache 

You're right, thank you for your suggestions and all the details! It should be ok now.
