### ISSUE TITLE
Article previews are of different heights

### ISSUE THREAD

**Issue by anshgyl** [Codeinwp/oria#34]
Even after setting the featured image to the same dimension on all the articles the front page has all article previews of different height and the page looks unsymmetrical.
Even after I added the following code to custom CSS the spacing between the previews remained unequal.
```
.item-sizer {
	height: 546px;
}
```

**Comment by ancapantilie** [comment]
@anshgyl Hi,

Oria is a masonry theme. This means that if your posts don't have the same height, they will be arranged according to the available vertical space.
In order to make the height of all posts the same, besides the dimension of the featured image, you should take into consideration other factors such as: the length of your article's title and the excerpt ( the excerpt is a brief description of the post).
